### PR TITLE
Phils 101 Guide

### PR DESCRIPTION
**Pull request by BlackstoneEngineering**
Putting this here as a place to keep track of it and review. Doesnt necessarily have to live here in final docs, just putting it here to keep track of it. 

@AnotherButler this is what I would like to talk with you about

### CODE REVIEW

**Comment by BlackstoneEngineering** [comment]
Closing this as I moved it to https://github.com/ARMmbed/Cloud-101-guide

**Comment by Phill1305** [comment]
I get a 404 error, is the URL (https://github.com/ARMmbed/Cloud-101-guide ) correct?

**Comment by iriark01** [comment]
You probably just don't have permission to view it.

**Comment by Phill1305** [comment]
Can't make many comments till I see it, was planning to have a read and edit as necessary.  Shall we use Microsoft Word and Office 365 instead? The one thing I did notice on the initial preview was the use of NXP LPC1768 which I think should be updated to something Cloud capable but that's as far as I got.

**Comment by iriark01** [comment]
No point in migrating to Microsoft; it will just add work (migrating is *not* automated; we have to manually fix everything Microsoft does).

**Comment by Phill1305** [comment]
I want to feel special and have access to the content, who do I need to speak nicely to?

**Comment by iriark01** [comment]
Austin

**Comment by BlackstoneEngineering** [comment]
Gave everyone permissions to the new repo. Should be working now. Docs team has admin access.

**Pull request closed without merging**
