### PR TITLE
Add script for updating notes to most recent doc pages

### PR DESCRIPTION
**Pull request by geky**
This script generates a note for each doc page that is out of date, with a link that takes users to the most recent doc page. If it can't find a recent doc page, it will ask the user which url to use. It uses existing notes and remembers answers in an effort to reduce the number questions forwarded to the user.

Originally I attempted to parse docs.json but could not get this to work well enough.

note: Don't merge until first successful run
cc @AnotherButler, @kegilbert

### CODE REVIEW

**Comment by AnotherButler** [comment]
@geky Is this OK to merge, or are we waiting on something?

**Comment by geky** [comment]
Hmmm, I'm not really sure. Does the script still work?

**Comment by AnotherButler** [comment]
Can I tell without merging it?

**Comment by geky** [comment]
If there's no one using it, then it's probably not worth merging at this point

**Comment by AnotherButler** [comment]
I think there's a use case for this. I would like to merge it if it's ready. I know at one point we were waiting on something before merging it, so I wanted to follow up and make sure it's OK to go now.

**Pull request merged**
