### PR TITLE
Rename LOWPOWERTIMER to LPTICKER

### PR DESCRIPTION
**Pull request by c1728p9**
Update the name in the docs to reflect the code.

### CODE REVIEW

**Comment by c1728p9** [comment]
Fixes #535

**Comment by AnotherButler** [comment]
@jen3andruska Once this is approved, please merge if you have time next week. If not, I'll take care of it when I come back :)

**Comment by jen3andruska** [comment]
@AnotherButler No problem. I'll keep an eye on it and merge once approved :)

**Comment by jen3andruska** [comment]
@AnotherButler All reviewers have approved, so I'm merging now ;)

**Pull request merged**
