### PR TITLE
Update Timer and related for precision + power

### PR DESCRIPTION
**Pull request by kjbracey-arm**
Rework out-of-date references to internal 32-bit precision.

Copy relevant note on power from Ticker to Timer and Timeout.

Resolves https://github.com/ARMmbed/mbed-os/issues/8312

### CODE REVIEW

**Comment by kjbracey-arm** [comment]
Suggest @bulislaw for review.

**Comment by kjbracey-arm** [comment]
@0xc0170, @yennster, @Arjun765

**Comment by yennster** [comment]
This note (https://github.com/ARMmbed/mbed-os-5-docs/blame/development/docs/api/drivers/Timer.md#L9) needs to be deleted as well

**Comment by AnotherButler** [comment]
ping @0xc0170

**Comment by AnotherButler** [comment]
@kjbracey-arm Please resolve the merge conflict.

**Pull request merged**
