### PR TITLE
Adding note for LoRaPHY & LoRaRadio clarification

### PR DESCRIPTION
**Pull request by hasnainvirk**
A note is added in the Technology section related to LoRaWAN.
It tries to clarify the difference between LoRaPHY and LoRaRadio.

### CODE REVIEW

**Comment by MarceloSalazar** [comment]
Thanks! LGTM

**Comment by AnotherButler** [comment]
Hey, @jen3andruska 
Could you please do a light copy edit on this change when you get a chance?

**Comment by jen3andruska** [comment]
@AnotherButler  No problem!

**Comment by jen3andruska** [comment]
@AnotherButler  Finished copy-editing that one change and made a few revisions.  Let me know if you need me to look at the entire document though...

**Comment by hasnainvirk** [comment]
@jen3andruska Thanks Jen for the review.

**Comment by jen3andruska** [comment]
@hasnainvirk  No problem, happy to help!

**Pull request merged**
