### PR TITLE
Update linker script templates to include stack

### PR DESCRIPTION
**Pull request by c1728p9**
Update the linker script templates to include the ability to adjust the boot stack stack size.

This depends on the code change here:
https://github.com/ARMmbed/mbed-os/pull/8039

### CODE REVIEW

**Comment by c1728p9** [comment]
Hi @deepikabhavnani, I set the default stack size to 4K to match the value in targets.json.  The RTOS mbed_lib.json overrides this to 1K when present.

This linker script template is for both 2 and 5. Are you wanting this to be stated more explicitly? Can you elaborate on what you would like updated in bootstrap.md?

**Comment by AnotherButler** [comment]
@deepikabhavnani Is this code OK to merge, or does @c1728p9 need to make further changes?

**Comment by deepikabhavnani** [comment]
Needs changes

**Comment by c1728p9** [comment]
Made changes and rebased to latest.

**Pull request merged**
