### PR TITLE
update with Fast Models Ethernet functions

### PR DESCRIPTION
**Pull request by jamesbeyond**
## Descriptions

Adding documentation for Fast Models Ethernet function and `mbed-os-example-socket`

### CODE REVIEW

**Comment by jamesbeyond** [comment]
Hi @AnotherButler, could you tag this PR as 5.11

**Comment by AnotherButler** [comment]
Is there a code dependency on this PR?

**Comment by jamesbeyond** [comment]
The code already merged to master

**Comment by MarceloSalazar** [comment]
We need this PR merged to get ready for OOB.

**Comment by jamesbeyond** [comment]
Thanks a lot! looking forward to having it merged

**Pull request merged**
