### PR TITLE
Socket constructors which call open are deprecated

### PR DESCRIPTION
**Pull request by michalpasztamobica**
Documentation update according to this code change: https://github.com/ARMmbed/mbed-os/pull/8794

### CODE REVIEW

**Comment by michalpasztamobica** [comment]
@SeppoTakalo  please review and add further reviewers if you approve.

**Comment by AnotherButler** [comment]
Is this for 5.11?

**Comment by SeppoTakalo** [comment]
Yes.

**Comment by AnotherButler** [comment]
This PR is only waiting on the code dependency.

**Comment by michalpasztamobica** [comment]
The code dependency has been merged to master ARMmbed/mbed-os#8794

**Pull request merged**
