### PR TITLE
Add docs on STCLK_OFF_DURING_SLEEP

### PR DESCRIPTION
**Pull request by c1728p9**
Update the docs to explain to STCLK_OFF_DURING_SLEEP.

### CODE REVIEW

**Comment by bcostm** [comment]
Just a remark: "ST" stands for Systick right ?

Is it possible to rename the macro in `SYSTICK_CLK_OFF_DURING_SLEEP`

Because it makes me think it's a macro for ST devices :)

**Comment by AnotherButler** [comment]
@c1728p9 What's the status of this? Have you addressed the comments?

**Comment by bulislaw** [comment]
@c1728p9 could we rename the flag both in code and here?

**Comment by c1728p9** [comment]
@bulislaw Yeah, I'll rename in both when I get around to this.

**Comment by AnotherButler** [comment]
@c1728p9 Are we expecting this for 5.10?

**Comment by c1728p9** [comment]
@AnotherButler this won't be coming in for 5.10.

I rebased this change, squashed it into one commit and renamed STCLK_OFF_DURING_SLEEP to SYSTICK_CLK_OFF_DURING_SLEEP. This has a code dependency on:
https://github.com/ARMmbed/mbed-os/pull/8108

**Comment by AnotherButler** [comment]
@c1728p9 Please resolve merge conflicts at your convenience.

**Comment by c1728p9** [comment]
Rebased to resolve merge conflicts

**Pull request merged**
