### PR TITLE
Revise contributing overview

### PR DESCRIPTION
**Pull request by theotherjimmy**
Actually list all of the sections

### CODE REVIEW

**Comment by SenRamakri** [comment]
@AnotherButler - Can we please know if we are still waiting on something to merge this?

**Comment by AnotherButler** [comment]
Based on user feedback, there's a proposal in place on the test site to remove "porting" from "contributing" and make it a top-level book. Because of this, the overview page may change, but it depends on proposal approval.

**Comment by AnotherButler** [comment]
@theotherjimmy Due to some irregularities with this task and some of the decisions around it, could you please put this PR against the 5.9 instead of development? [But keep putting PRs against development normally?]

**Comment by theotherjimmy** [comment]
@AnotherButler Yeah, no problem. Just a moment.

**Comment by theotherjimmy** [comment]
@AnotherButler Done.

**Pull request merged**
