### PR TITLE
Initial commit of Intro to Mbed OS workshop

### PR DESCRIPTION
**Pull request by BlackstoneEngineering**
Original file this is based on can be found here : https://docs.google.com/document/d/1n_1X3S2-1g5gOIqLGEST_Lt6382dCteA4Q4ZhN6IKyE/edit# 

all images are base64 encoded directly into the doc. 

Please edit for correctness in the docs engine. I did my best to get everything done, but there is deffinantly some weirdness around getting the list numbering to work correctly.

### CODE REVIEW

**Comment by BlackstoneEngineering** [comment]
For reference here are all images used in this doc : [images.zip](https://github.com/ARMmbed/Handbook/files/2065182/images.zip)

**Comment by BlackstoneEngineering** [comment]
This is the workshop I gave in May 2018, intro to mbed OS. Submitting here so I can give references to other people. I really want the workshop content to live on the website and not in google docs. 

Please review / accept / edit 

@AnotherButler

**Comment by iriark01** [comment]
@BlackstoneEngineering this won't even show the diff, and I can't load the file itself for preview. Is there something wrong with it, or is it GitHub being funny?

**Comment by BlackstoneEngineering** [comment]
@iriark01 Github being github. If you build it in the docs system you can see it. 

PS: Github preview is not a reliable method of preview, as our docs system uses a super set of github flavored markdown. It would be really good to have a 'preview' button or something similar in the docs engine so we could easily view these kinds of things.

**Comment by iriark01** [comment]
Well I *do* know how to do Engine-flavoured MD and I would like to be able to review this PR as a PR for a while. Can you do some GH magic to make it work?

**Comment by BlackstoneEngineering** [comment]
I don't know how to make GitHub process it. I recommend building it in the
docs system. I had to build it locally

**Comment by iriark01** [comment]
What is wrong with it that makes GB refuse?

**Comment by BlackstoneEngineering** [comment]
No clue, didn't test it with GitHub. I tested it with the docs engine and
it works fine

**Comment by iriark01** [comment]
Please remove your image embedding and we'll link to them properly. That might fix the break. 

I am not handling this PR at this state.

**Comment by iriark01** [comment]
Pending a meeting with Austin and Gary to make sure we have a single, full set of docs to support as many workshops as possible.

**Comment by BlackstoneEngineering** [comment]
@iriark01 , thats 2 weeks out. I would prefer not to have this blocked for 2 weeks.

**Comment by iriark01** [comment]
We have bigger plans than just your two workshops and we're not doing this twice. 

It wouldn't have been done before 5.9 goes out either way; there's not enough bandwidth.

**Pull request closed without merging**
